### ISSUE TITLE
removing testing dependencies and files

### ISSUE THREAD

**Issue by mattxwang** [uclaacm/teach-la-react-starter-barebones#49]
When I originally made this barebones template, I included everything bundled with `create-react-app`, which includes some supporting Jest libraries and the default `App.test.js` file. Unfortunately, I don't think any of our projects that actually use this template write any tests or use Jest.

I don't think they're doing anything bad at the moment, but I see two slight pitfalls:

* we get overloaded with Jest-related dependabot updates like #47 and #48, which need to be replicated downstream as well
* there's more boilerplate files for someone else to understand 

So, the question is - should we remove these files? Note that no matter, what, `react-scripts` will still bundle Jest into our dependency tree, and it's going to be in our `package-lock.json` anyways. Curious what y'all think!

cc: @reginawang99 @matthewcn56 @ellieyhcheng @doubleiis02

**Comment by reginawang3495** [comment]
I believe there was some discussion around whether we wanted our LLs to have testing, and I believe we came to a slight conclusion that it wasn't necessary unless there were utils that we really wanted to test. Because of that, I think the tests are sort of just bloating the files, so I'm down to remove them!

Also, as a side note, I believe we are mainly switching to TS+Yarn and getting our new LLs to use the other template if I recall correctly.
